# Generated by Django 5.0.6 on 2024-07-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_delete_post_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=250),
        ),
    ]
