# Generated by Django 5.0.6 on 2024-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
