# Generated by Django 5.0.6 on 2024-10-17 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_profile_location_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='phoneNumber',
            field=models.CharField(default='0712345678', max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
    ]
