# Generated by Django 5.0.6 on 2024-10-17 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_resource_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
    ]
