# Generated by Django 5.0.6 on 2024-10-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_remove_profile_phone_number_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
