# Generated by Django 5.0.6 on 2024-10-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alert_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='location',
            field=models.CharField(default='unknown', max_length=200),
        ),
    ]
