# Generated by Django 5.0.6 on 2024-10-17 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_resource_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
