# Generated by Django 5.0.6 on 2024-10-17 13:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_rename_resource_type_resourcerequest_resource_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.resource'),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
    ]
