# Generated by Django 5.0.6 on 2024-10-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_remove_resourcerequest_resource_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.resource'),
        ),
    ]
