# Generated by Django 5.0.6 on 2024-10-17 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_resourcerequest_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='phoneNumber',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d*$')]),
        ),
    ]
