# Generated by Django 5.0.6 on 2024-10-17 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_remove_resourcerequest_resource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='Resource_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
