# Generated by Django 5.0.7 on 2024-10-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_resourcerequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='location',
        ),
    ]
