# Generated by Django 5.1.2 on 2024-10-19 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0031_remove_profile_location_profile_emergency_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="emergency_contact",
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phoneNumber",
            field=models.CharField(
                default=" ",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only numeric values are allowed", regex="^\\d*$"
                    )
                ],
            ),
        ),
    ]
