# Generated by Django 5.1.2 on 2024-10-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0032_remove_profile_emergency_contact_profile_location_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="organization",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
